services:
  - type: web
    name: chatbox
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PORT
        value: 8000
    build:
      pythonVersion: 3.11.13
      